// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaEnlace.API.Data;

#nullable disable

namespace SistemaEnlace.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240521132350_Relaciones")]
    partial class Relaciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaEnlace.Shared.Entities.Conversacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("JovenVulnerableid")
                        .HasColumnType("int");

                    b.Property<int>("Tutorid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("JovenVulnerableid");

                    b.HasIndex("Tutorid");

                    b.ToTable("conversacions");
                });

            modelBuilder.Entity("SistemaEnlace.Shared.Entities.Formulario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Conversacionid")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fundacionid")
                        .HasColumnType("int");

                    b.Property<string>("Resumen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Supervisorid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Conversacionid");

                    b.HasIndex("Fundacionid");

                    b.HasIndex("Supervisorid");

                    b.ToTable("formularios");
                });

            modelBuilder.Entity("SistemaEnlace.Shared.Entities.Fundacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("fundacions");
                });

            modelBuilder.Entity("SistemaEnlace.Shared.Entities.JovenVulnerable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("FundacionId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Situacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("id");

                    b.HasIndex("FundacionId");

                    b.ToTable("JovenesVulnerables");
                });

            modelBuilder.Entity("SistemaEnlace.Shared.Entities.Supervisor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("id");

                    b.ToTable("supervisors");
                });

            modelBuilder.Entity("SistemaEnlace.Shared.Entities.Tutor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("Experiencia")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("id");

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("SistemaEnlace.Shared.Entities.Conversacion", b =>
                {
                    b.HasOne("SistemaEnlace.Shared.Entities.JovenVulnerable", "JovenesVulnerables")
                        .WithMany("conversacions")
                        .HasForeignKey("JovenVulnerableid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaEnlace.Shared.Entities.Tutor", "Tutores")
                        .WithMany("conversacions")
                        .HasForeignKey("Tutorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JovenesVulnerables");

                    b.Navigation("Tutores");
                });

            modelBuilder.Entity("SistemaEnlace.Shared.Entities.Formulario", b =>
                {
                    b.HasOne("SistemaEnlace.Shared.Entities.Conversacion", "conversaciones")
                        .WithMany()
                        .HasForeignKey("Conversacionid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaEnlace.Shared.Entities.Fundacion", "fundaciones")
                        .WithMany()
                        .HasForeignKey("Fundacionid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaEnlace.Shared.Entities.Supervisor", "supervisores")
                        .WithMany()
                        .HasForeignKey("Supervisorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("conversaciones");

                    b.Navigation("fundaciones");

                    b.Navigation("supervisores");
                });

            modelBuilder.Entity("SistemaEnlace.Shared.Entities.JovenVulnerable", b =>
                {
                    b.HasOne("SistemaEnlace.Shared.Entities.Fundacion", "Fundaciones")
                        .WithMany("JovenesVulnerables")
                        .HasForeignKey("FundacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fundaciones");
                });

            modelBuilder.Entity("SistemaEnlace.Shared.Entities.Fundacion", b =>
                {
                    b.Navigation("JovenesVulnerables");
                });

            modelBuilder.Entity("SistemaEnlace.Shared.Entities.JovenVulnerable", b =>
                {
                    b.Navigation("conversacions");
                });

            modelBuilder.Entity("SistemaEnlace.Shared.Entities.Tutor", b =>
                {
                    b.Navigation("conversacions");
                });
#pragma warning restore 612, 618
        }
    }
}
