// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaEnlace.API.Data;

#nullable disable

namespace SistemaEnlace.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaEnlace.Shared.Entities.Actividad", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Participantes")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("id");

                    b.ToTable("actividads");
                });

            modelBuilder.Entity("SistemaEnlace.Shared.Entities.Conversacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("participantes")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("conversacions");
                });

            modelBuilder.Entity("SistemaEnlace.Shared.Entities.Fundacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Personaid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Personaid");

                    b.ToTable("fundacions");
                });

            modelBuilder.Entity("SistemaEnlace.Shared.Entities.Persona", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("id");

                    b.ToTable("personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SistemaEnlace.Shared.Entities.Realiza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodActivi")
                        .HasColumnType("int");

                    b.Property<int>("DniPersona")
                        .HasColumnType("int");

                    b.Property<int>("actividadid")
                        .HasColumnType("int");

                    b.Property<int>("personaid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("actividadid");

                    b.HasIndex("personaid");

                    b.ToTable("realizas");
                });

            modelBuilder.Entity("SistemaEnlace.Shared.Entities.Supervisa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodActi")
                        .HasColumnType("int");

                    b.Property<int>("DniSup")
                        .HasColumnType("int");

                    b.Property<int>("actividadid")
                        .HasColumnType("int");

                    b.Property<int>("supervisorid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("actividadid");

                    b.HasIndex("supervisorid");

                    b.ToTable("supervisas");
                });

            modelBuilder.Entity("SistemaEnlace.Shared.Entities.Supervisor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("id");

                    b.ToTable("supervisors");
                });

            modelBuilder.Entity("SistemaEnlace.Shared.Entities.JovenVulnerable", b =>
                {
                    b.HasBaseType("SistemaEnlace.Shared.Entities.Persona");

                    b.Property<string>("Situacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("JovenVulnerable");
                });

            modelBuilder.Entity("SistemaEnlace.Shared.Entities.Tutor", b =>
                {
                    b.HasBaseType("SistemaEnlace.Shared.Entities.Persona");

                    b.Property<int>("Experiencia")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Tutor");
                });

            modelBuilder.Entity("SistemaEnlace.Shared.Entities.Fundacion", b =>
                {
                    b.HasOne("SistemaEnlace.Shared.Entities.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("Personaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SistemaEnlace.Shared.Entities.Realiza", b =>
                {
                    b.HasOne("SistemaEnlace.Shared.Entities.Actividad", "actividad")
                        .WithMany("Realizas")
                        .HasForeignKey("actividadid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaEnlace.Shared.Entities.Persona", "persona")
                        .WithMany("Realizas")
                        .HasForeignKey("personaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("actividad");

                    b.Navigation("persona");
                });

            modelBuilder.Entity("SistemaEnlace.Shared.Entities.Supervisa", b =>
                {
                    b.HasOne("SistemaEnlace.Shared.Entities.Actividad", "actividad")
                        .WithMany("Supervisar")
                        .HasForeignKey("actividadid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaEnlace.Shared.Entities.Supervisor", "supervisor")
                        .WithMany("Supervisar")
                        .HasForeignKey("supervisorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("actividad");

                    b.Navigation("supervisor");
                });

            modelBuilder.Entity("SistemaEnlace.Shared.Entities.Actividad", b =>
                {
                    b.Navigation("Realizas");

                    b.Navigation("Supervisar");
                });

            modelBuilder.Entity("SistemaEnlace.Shared.Entities.Persona", b =>
                {
                    b.Navigation("Realizas");
                });

            modelBuilder.Entity("SistemaEnlace.Shared.Entities.Supervisor", b =>
                {
                    b.Navigation("Supervisar");
                });
#pragma warning restore 612, 618
        }
    }
}
